### ISSUE TITLE
remote expel lua error

### ISSUE THREAD

**Issue by randy0030** [emptyrivers/BrewmasterTools#11]
I've been getting this error a lot ever since I have updated the brewmaster addon through curse. It happens most often whenever I get a healing sphere stack. 

----
Message: Interface\AddOns\BrewmasterTools\remoteExpel.lua:18: bad argument #1 to 'format' (string expected, got nil)
Time: 08/15/17 02:59:29
Count: 120
Stack: Interface\AddOns\BrewmasterTools\remoteExpel.lua:18: bad argument #1 to 'format' (string expected, got nil)Interface\SharedXML\SharedBasicControls.lua:189: in function <Interface\SharedXML\SharedBasicControls.lua:187>
Interface\SharedXML\SharedBasicControls.lua:204: in function <Interface\SharedXML\SharedBasicControls.lua:203>
[C]: ?
[C]: in function `format'
Interface\AddOns\BrewmasterTools\remoteExpel.lua:18: in function <Interface\AddOns\BrewmasterTools\remoteExpel.lua:12>

Locals: errorTypeCVar = "scriptErrors"
warnType = false
msg = "Interface\AddOns\BrewmasterTools\remoteExpel.lua:18: bad argument #1 to 'format' (string expected, got nil)"
messageType = 0
hideErrorFrame = false
IsErrorCVarEnabled = <function> defined @Interface\SharedXML\SharedBasicControls.lua:183

**Comment by emptyrivers** [comment]
Fixed in #12
