### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by mryanlam** [emptyrivers/BrewmasterTools#16]
* Explain what you were doing when the error occured:
After login it occurs

* Do you have an error log? If so, put it here:
Message: Interface\AddOns\BrewmasterTools\load.lua:15: attempt to index global 'BRMTOOL' (a nil value)
Time: 11/17/17 19:07:15
Count: 1
Stack: Interface\AddOns\BrewmasterTools\load.lua:15: attempt to index global 'BRMTOOL' (a nil value)
[C]: ?
Interface\AddOns\BrewmasterTools\load.lua:15: in function <Interface\AddOns\BrewmasterTools\load.lua:9>

Locals: 

* What version of BrewmasterTools are you using?
v0.2.1

* When was the last version which did not have this issue?

**Comment by emptyrivers** [comment]
Fixed in 0.2.2.

**Comment by emptyrivers** [comment]
Fixed in 0.2.2.
