### ISSUE TITLE
Couple of Errors in 8.0.1

### ISSUE THREAD

**Issue by spliffmaster** [emptyrivers/BrewmasterTools#20]
**First:**

5x [string "--[[ Error in ' Normalized Stagger' ]]retur..."]:8: attempt to perform arithmetic on a nil value
[C]: in function `xpcall'
WeakAuras\WeakAuras-2.6.0.lua:2866: in function <WeakAuras\WeakAuras.lua:2772>

Locals:
nil

**Second:**

5x [string "--[[ Error in ' Normalized Stagger' ]]retur..."]:8: attempt to perform arithmetic on a nil value
[C]: in function `xpcall'
WeakAuras\WeakAuras-2.6.0.lua:2866: in function <WeakAuras\WeakAuras.lua:2772>

Locals:
nil

**Comment by emptyrivers** [comment]
Fixed in the next release.
