### ISSUE TITLE
Normalized stagger WA error

### ISSUE THREAD

**Issue by Stormcro** [emptyrivers/BrewmasterTools#21]
* Explain what you were doing when the error occured:
- Anytime the normalized stagger weakaura is accessed, a lua spam occurs. consistently spams when WA is loaded, or previewed, both in and out of combat. IsB tracker is fine. 

* Do you have an error log? If so, put it here:
-     [string "--[[ Error in ' Normalized Stagger' ]]retur..."]:4: attempt to perform arithmetic on a nil value
[C]: in function `xpcall'
WeakAuras\RegionTypes\AuraBar.lua:1292: in function `UpdateCustomText'
WeakAuras\WeakAuras-2.6.0.lua:3544: in function <WeakAuras\WeakAuras.lua:3538>

Locals:
nil

* What version of BrewmasterTools are you using?
-  0.3.0

* When was the last version which did not have this issue?
-  i have never used this add on WA combo before. re-rolling for BfA to BrM.

**Comment by Stormcro** [comment]
The pasting format came through odd, i hope that provides the info you need. 

Thank you very much for your time!

**Comment by emptyrivers** [comment]
Fixed in the next release.
