### ISSUE TITLE
staggerPause.lua UNIT_SPELLCAST_SUCCEEDED

### ISSUE THREAD

**Issue by Ironii** [emptyrivers/BrewmasterTools#24]
* Explain what you were doing when the error occured:
staggerPause.lua UNIT_SPELLCAST_SUCCEEDED event handler is outdated

* Do you have an error log? If so, put it here:

* What version of BrewmasterTools are you using?
newest

* When was the last version which did not have this issue?

**Comment by FlappingArms** [comment]
I think this one can be closed. Was fixed in 0.3.2 and i tested it on my monk.
