### ISSUE TITLE
Removed Second Bar?

### ISSUE THREAD

**Issue by plachance14** [emptyrivers/BrewmasterTools#25]
Hi, this isn't necessarily an issue, more of a question.  In most of the screenshots and descriptions of the addon + the WA two bars are shown/described (One for normal stagger, one for normalized stagger).  When I got the addon, and the WA I am only getting one bar, which I believe is normalized stagger.  Is the bar you have shown in previous screenshots no longer part of the WA/addon pairing, or was their another WA/addon you were using to display it?

**Comment by emptyrivers** [comment]
That screenshot is very old, and if you inspect it closely you'll see that it's actually a comparison of a regular stagger bar (normalized against max hp), and normalized stagger.
